apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodetest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejstest
  template:
    metadata:
      labels:
        app: nodejstest
    spec:
      container:
      - name: mynodetestcontainer
        image: tharun13055/nodetest:v1
        ports:
        - containerPort: 80